algTypes: [ "SMJ" ] # "NLJ" | "HJ" | "SMJ"
deviceTypes: [ "CPU" ] # "CPU" |"GPU"
progressivenessModes: [ "LAZY" ] # "EAGER" |"LAZY"
distinctKeys: [ 1000 ] # Number of distinct keys in each streams
zipfThetas: [ 0.0 ] # Zipf theta parameter
resultMaterializationMethod: [ "NoOutput" ] # "CountKernel" | "EstimatedSelectivity" | "Bitmap" | "Atomic"
windowSizesMB: [ 16, 32 ] # Window sizes in Megabyte(s)
batchSizeKB: [ 128 ] # Batch sizes in Kilobyte(s)
measuredMetric: "Throughput"  # "Throughput" | "cumulativePercentage"
measurePowerUsage: "No"  # "Yes" | "No"
repeat: 5 # number of runs per configuration
parStrats: [ "INTER", "INTRA", "HYBRID" ] # "INTER" |"INTRA" | "HYBRID"
